name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          registry-url: 'https://registry.npmjs.org'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER:  docs/.vuepress/dist
